### ISSUE TITLE
How to disable in a particular repo?

### ISSUE THREAD

**Issue by paddyroddy** [errata-ai/vale-vscode#34]
I have a repo where I do not require `vale`. In the repos that I do want `vale` I use the CLI and it works well - I have a `.vale.ini` file in that repo (i.e. not system wide). But in this other repo I keep getting errors like this
![image](https://user-images.githubusercontent.com/15052188/101393315-d2697380-38be-11eb-83b6-ad6696765950.png)

My `settings.json` just has `"vale.core.useCLI": true`. How can I stop this error?

**Comment by ChrisChinchilla** [comment]
Just to clarify @paddyroddy I feel like the question here is more "how to I disable Vale in a repo/project?"

I personally generally do this from the VSCode level, i.e. disable the extension per workspace, but I appreciate this takes work. I am not sure how to get around that as Vale tends to inherit config from upper levels in the file system, so if you don't have a config in the current directory, it takes one from the level up etc…

That said, this error is interesting, and shouldn't really be related, unless there's an error in some upper level config file. It's also an error I thought we had fixed, so which version of the extension are you using?

**Comment by paddyroddy** [comment]
Yeah, I guess at the moment I have a bunch of extensions that I always keep enabled even when not relevant to that project (just for ease). So ideally I wouldn't want to make an exception just for `vale`.

My extension version is `0.14.0` and the file in particular that vale is moaning about is my `launch.json` which for this project looks like
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "plotting",
            "type": "python",
            "request": "launch",
            "module": "pys2sleplet.scripts.plotting",
            "args": ["slepian"]
        },
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}
```

**Comment by ChrisChinchilla** [comment]
@paddyroddy That is the latest version… I have a feeling then that maybe the config file that Vale is using when there isn't a local file present is checking all file types? Possibly you should tweak that to only check markdown, rst, etc etc? See docs here - https://docs.errata.ai/vale/config#options

**Comment by paddyroddy** [comment]
Okay thanks for the help. I'm aware and do use that feature when using `vale`. But to my knowledge I haven't set one at the top level - I only create one local to a repo

**Comment by jdkato** [comment]
I think the problem here is that the extension is unable to find a config file -- case (2) mentioned below.

https://github.com/errata-ai/vale-vscode/blob/7cbd30bf47ed1cb4cb5bbb378fad9db17c6fbe6c/src/features/vsProvider.ts#L67-L74

It should be fixed by #38 in the sense that the error will be logged to our output panel rather sending a disruptive UI pop up.

**Comment by jdkato** [comment]
v0.14.1 is out now and should resolve this issue.

**Comment by paddyroddy** [comment]
I'm not sure if this is related but since the latest version (`0.14.1`) it keeps popping up with
![image](https://user-images.githubusercontent.com/15052188/102356676-6f09d080-3fa5-11eb-8344-46f5b3ac97ec.png)

**Comment by jdkato** [comment]
This seems like a configuration error, but it's not immediately clear to me what could be causing it.

1. Does it happen only on repos without a `.vale.ini` file?
2.  Have you edited `vale.valeCLI.path`?

**Comment by ChrisChinchilla** [comment]
So @paddyroddy and @jdkato I also sporadically get this error, but I don't get it with just Vale, I get it with other extensions that look for a binary. So far all I've managed to track down is if you open VScode from a non-normal way, for example I use a Git gui called Fork, and it has a menu bar item that lets you open your editor. If I use that, then no extensions find binaries, I think also sometimes if I use `code` to open a file.

So I am not sure if this is an error with this extension, or if it is, it's because we're using the "wrong way" to locate a binary, as are many other extensions! I've tried to do some searching around this, but it's a really hard error to search for.

**Comment by paddyroddy** [comment]
1. I'm in a repo without a `.vale.ini` file, i.e. I have no intention of using `vale` in this repo
2. No I have not edited it

@ChrisChinchilla so I _think_ I only get this message with `vale` but I may be wrong. I normally open `vscode` from spotlight on mac or clicking an icon
